{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "METADATA_FILE_PATH = \"coeffs.csv\"\n",
    "prefix = \"/localtmp/as9rw/datasets/botnet_temp/\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import deepdish as dd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load metadata file\n",
    "names, values = [], []\n",
    "with open(METADATA_FILE_PATH, 'r') as f:\n",
    "    for line in f:\n",
    "        n, v = line.rstrip(\"\\n\").split(',')\n",
    "        names.append(\"/\" + n)\n",
    "        values.append(float(v))\n",
    "    names = np.array(names)\n",
    "    values = np.array(values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array([26., 29., 52., 87., 65., 62., 46., 57., 55.,  9.]),\n",
       " array([0.00334518, 0.00405657, 0.00476795, 0.00547934, 0.00619073,\n",
       "        0.00690211, 0.0076135 , 0.00832489, 0.00903627, 0.00974766,\n",
       "        0.01045905]),\n",
       " <a list of 10 Patch objects>)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXAAAAD4CAYAAAD1jb0+AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+j8jraAAAN20lEQVR4nO3df4ykB13H8ffHHqXtoW1p16b0kD0CQQ+i/LiUYrEhHImFkrYxhNSoKaSmMSLywwQOSUT8q41EwGAwl1ZyKtLWEy2hEcFaDMR4uEeLtD2Qa3uFqy1dlIJgBCpf/5indrvd6053Zm7nC+9Xstl5fn9ubuazzzzPPDOpKiRJ/fzIZgeQJG2MBS5JTVngktSUBS5JTVngktTUlmO5sdNPP70WFxeP5SYlqb0DBw58raoWVo8/pgW+uLjI0tLSsdykJLWX5O61xnsIRZKassAlqSkLXJKassAlqSkLXJKassAlqSkLXJKassAlqSkLXJKaOqZXYqqHxd03bNq2D19xwaZtW+rGPXBJasoCl6SmLHBJasoCl6SmLHBJasoCl6SmLHBJasoCl6SmLHBJasoCl6SmLHBJasoCl6SmxirwJG9KcluSW5N8KMkJSbYn2Z/kUJJrkxw/67CSpIetW+BJzgJ+E9hZVc8BjgMuAa4E3l1VzwC+Dlw2y6CSpEca9xDKFuDEJFuAk4B7gZcC+4bpe4GLpx9PknQ06xZ4Vd0DvAv4MqPi/gZwAHigqh4cZjsCnLXW8kkuT7KUZGl5eXk6qSVJYx1CORW4CNgOPAXYCpw/7gaqak9V7ayqnQsLCxsOKkl6pHEOobwMuKuqlqvqe8CHgXOBU4ZDKgDbgHtmlFGStIZxCvzLwDlJTkoSYBdwO3AT8KphnkuB62cTUZK0lnGOge9ndLLys8Dnh2X2AG8F3pzkEHAacPUMc0qSVhnrS42r6h3AO1aNvhM4e+qJJElj8UpMSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekprZsdgBppcXdN2zKdg9fccGmbFeahHvgktSUBS5JTVngktSUBS5JTVngktSUBS5JTfk2QonNe/si+BZGbZx74JLU1FgFnuSUJPuSfCHJwSQvSvLkJJ9I8qXh96mzDitJeti4e+DvBT5WVT8J/AxwENgN3FhVzwRuHIYlScfIugWe5GTgPOBqgKr6blU9AFwE7B1m2wtcPKuQkqRHG2cPfDuwDHwgyc1JrkqyFTijqu4d5rkPOGOthZNcnmQpydLy8vJ0UkuSxirwLcDzgfdX1fOAb7PqcElVFVBrLVxVe6pqZ1XtXFhYmDSvJGkwToEfAY5U1f5heB+jQv9qkjMBht/3zyaiJGkt6xZ4Vd0HfCXJs4ZRu4DbgY8Alw7jLgWun0lCSdKaxr2Q5/XAB5McD9wJvJZR+V+X5DLgbuDVs4koSVrLWAVeVbcAO9eYtGu6cSRJ4/JKTElqys9CkX5I+fkv/bkHLklNWeCS1JQFLklNWeCS1JQnMSUdc5t1AvUH7eSpe+CS1JQFLklNWeCS1JQFLklNWeCS1JQFLklN+TbCObaZn1Uhaf65By5JTVngktSUBS5JTVngktSUBS5JTVngktSUBS5JTVngktSUBS5JTVngktSUBS5JTVngktSUBS5JTflphNIm81MntVHugUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDU1doEnOS7JzUk+OgxvT7I/yaEk1yY5fnYxJUmrPZ498DcAB1cMXwm8u6qeAXwduGyawSRJj22sAk+yDbgAuGoYDvBSYN8wy17g4lkElCStbdw98PcAbwG+PwyfBjxQVQ8Ow0eAs6acTZL0GNYt8CSvBO6vqgMb2UCSy5MsJVlaXl7eyCokSWsYZw/8XODCJIeBaxgdOnkvcEqShz5PfBtwz1oLV9WeqtpZVTsXFhamEFmSBGMUeFW9raq2VdUicAnwD1X1S8BNwKuG2S4Frp9ZSknSo0zyPvC3Am9OcojRMfGrpxNJkjSOx/WValX1SeCTw+07gbOnH0mSNA6vxJSkpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekpixwSWrKApekph7Xt9L/MFrcfcNmR5CkNbkHLklNWeCS1JQFLklNWeCS1JQFLklNWeCS1FSbtxH6dj5JeiT3wCWpKQtckpqywCWpKQtckpqywCWpKQtckpqywCWpKQtckpqywCWpKQtckppat8CTPDXJTUluT3JbkjcM45+c5BNJvjT8PnX2cSVJDxlnD/xB4LeqagdwDvC6JDuA3cCNVfVM4MZhWJJ0jKxb4FV1b1V9drj9X8BB4CzgImDvMNte4OJZhZQkPdrjOgaeZBF4HrAfOKOq7h0m3QeccZRlLk+ylGRpeXl5gqiSpJXGLvAkTwL+CnhjVX1z5bSqKqDWWq6q9lTVzqraubCwMFFYSdLDxirwJE9gVN4frKoPD6O/muTMYfqZwP2ziShJWss470IJcDVwsKr+YMWkjwCXDrcvBa6ffjxJ0tGM84085wK/Anw+yS3DuN8GrgCuS3IZcDfw6tlElCStZd0Cr6pPAznK5F3TjSNJGpdXYkpSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDVlgUtSUxa4JDU1zrfSS9IPhMXdN2zKdg9fccFM1useuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMWuCQ1ZYFLUlMTFXiS85N8McmhJLunFUqStL4NF3iS44A/Al4O7AB+McmOaQWTJD22SfbAzwYOVdWdVfVd4BrgounEkiStZ5JvpT8L+MqK4SPAC1fPlORy4PJh8DtJbp1gm8fS6cDXNjvEmMw6fV1ygllnZWpZc+XEq3jaWiMnKfCxVNUeYA9AkqWq2jnrbU6DWWejS9YuOcGss9Ih6ySHUO4BnrpieNswTpJ0DExS4P8CPDPJ9iTHA5cAH5lOLEnSejZ8CKWqHkzyG8DfAccBf1JVt62z2J6Nbm8TmHU2umTtkhPMOitznzVVtdkZJEkb4JWYktSUBS5JTc30UvokT0xy7TB9f5LFFdPeNoz/YpKfH8adkOQzST6X5LYk75wk3yyzrph2XJKbk3x0XnMmOZzk80luSbI0jZwzzHpKkn1JvpDkYJIXzWPWJM8a7s+Hfr6Z5I3zmHUY/6bhOXVrkg8lOWFOc75hyHjbtO7PSbImOS3JTUm+leR9q5Z5wfC8OpTkD5NkWnnHVlUb+mF04vIO4OnA8cDngB2r5vl14I+H25cA1w63dwzzPxHYPqznOCDAk4Z5ngDsB87ZaMZZZl2x3JuBvwA+Oq85gcPA6ZPmO0ZZ9wK/Otw+HjhlXrOuWv99wNPmMSuji+7uAk4c5rsOeM0c5nwOcCtwEqM3WPw98IxNvk+3Ai8Gfg1436plPgOcw6i3/hZ4+TSfY+P8zPpS+osYPSEB9gG7hr9SFwHXVNV3quou4BBwdo18a5j/CcPPNM6yTj0rQJJtwAXAVVPIOLOcMzL1rElOBs4Drgaoqu9W1QPzmHXVsruAO6rq7jnOugU4MckWRgX573OY86eA/VX131X1IPCPwC9MmHOirFX17ar6NPA/K2dOcibwY1X1zzVq8z8FLp5C1sdlkgJf61L6s442z/Af8g3gtMdaNqNDErcA9wOfqKr9E2ScaVbgPcBbgO9PIeMscxbw8SQHMvpog3nNuh1YBj6Q0WGpq5JsndOsK10CfGgKOWeStaruAd4FfBm4F/hGVX183nIy2vv+ueGwxUnAK3jkxYKbkfWx1nlknXXO3NydxKyq/62q5zK6svPsJM/Z7ExrSfJK4P6qOrDZWcbw4qp6PqNPjnxdkvM2O9BRbAGeD7y/qp4HfBuY648pzugitguBv9zsLEeT5FRGe5jbgacAW5P88uamerSqOghcCXwc+BhwC/C/mxpqzs36Uvr/n2d46XYy8B/jLDu8dL4JOH+CjLPMei5wYZLDjF6SvTTJn89hToY9MKrqfuCvmc6hlVlkPQIcWfGqax+jQp/HrA95OfDZqvrqFHLOKuvLgLuqarmqvgd8GPjZOcxJVV1dVS+oqvOArwP/NmHOSbM+1jq3rbPO2ZvgxMAW4E5Gf9UfOjHw7FXzvI5Hnhi4brj9bB55EuNORicaFhhOWgEnAp8CXjnpgf5ZZF217EuYzknMWdynW4EfrYdPyPwTcP48Zh2mfQp41nD7d4Hfn9esw/RrgNdOmnHGj4EXArcxOvYdRsd6Xz9vOYdpPz78/gngC0znJPaGs66Y/hrWP4n5imk9Dsb+t014x7yC0V/IO4C3D+N+D7hwuH0Co5eWh4Z/7NNXLPv2YbkvMpy9BX4auBn4V0bHw35nik+MqWZdte6XMIUCn9F9+vThAfu54Un89nm+T4HnAkvDY+BvgFPnOOtWRntpJ0/rPp1h1ncyKsRbgT8DnjinOT8F3D48XnfNyX16GPhP4FuMXiXuGMbvHO7PO4D3MVzZfix/vJRekpqau5OYkqTxWOCS1JQFLklNWeCS1JQFLklNWeCS1JQFLklN/R/NcAnlfg60BgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.hist(values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "prop_0 = np.where(values <= 0.0063)[0]\n",
    "prop_1 = np.where(values >= 0.0073)[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(201, 200)"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(prop_0), len(prop_1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "wanted_0 = names[prop_0]\n",
    "wanted_1 = names[prop_1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "wanted_0_graphs = dd.io.load(os.path.join(self.path, graph_name), wanted_0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load julaugsep files\n",
    "julaugsep = dd.io.load(prefix + \"all_graphs_julaugsep.hdf5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load may files\n",
    "may = dd.io.load(prefix + \"all_graphs_may.hdf5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load june files\n",
    "jun = dd.io.load(prefix + \"all_graphs_jun.hdf5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load everything else\n",
    "else_all = dd.io.load(prefix + \"all_graphs.hdf5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "may_june = {**may, **jun}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-130900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-131900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-132900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-133900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-134900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-135900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180517-140000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-130900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-131900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-132900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-133900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-134900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135100.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135200.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135300.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135400.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135500.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135600.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135700.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135800.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-135900.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n",
      "/u/as9rw/anaconda3/envs/phd/lib/python3.6/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'equinix-nyc.dirA.20180621-140000.UTC.anon.hdf5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n",
      "  check_attribute_name(name)\n"
     ]
    }
   ],
   "source": [
    "dd.io.save(prefix + \"all_graphs_mayjune.hdf5\", may_june)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "len(aug_sep)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_of_em = {**aug, **jul, **sep, **else_all}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "len(all_of_em)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dd.io.save(prefix + \"legit_all.hdf5\", all_of_em)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "phd",
   "language": "python",
   "name": "phd"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
